export { default as NewCoinFlip } from './NewCoinFlip';
export { default as RevealView } from './RevealView';
export { default as StatusToast } from './StatusToast';
export { default as ResultView } from './ResultView';
export { default as Coin } from './Coin';
export { default as FreeBetModal } from './FreeBetModal';
export { default as BetHistory } from './BetHistory';
export { default as BettingView } from './BettingView';
export { default as ConfettiComponent } from './ConfettiComponent';
export { CatCoinSVG, TailCoinSVG } from './CoinSVG'; 